### ISSUE TITLE
Dependency list

### ISSUE THREAD

**Issue by brunelli** [murraycu/prefixsuffix#1]
Hello!

I just saw your blog post in planet.gnome.org, tested your program, and decided to create the [`prefixsuffix`](https://aur.archlinux.org/packages/prefixsuffix/) and the [`prefixsuffix-git`](https://aur.archlinux.org/packages/prefixsuffix-git/) AUR packages.

So far the dependencies I'm listing are:

```
depends=('gtkmm3')
makedepends=('gnome-common' 'mm-common')
```

Could you please tell me if something is missing?

**Comment by murraycu** [comment]
Thanks. That looks correct.

**Comment by brunelli** [comment]
Okay, thank you very much for making this app :)
