### ISSUE TITLE
Wrong file renaming when selecting "Preffix" while I should have selected "Suffix"

### ISSUE THREAD

**Issue by brunelli** [murraycu/prefixsuffix#5]
So, this happened:

![captura de tela de 2015-05-14 16-23-28](https://cloud.githubusercontent.com/assets/5755892/7639997/a46383ec-fa56-11e4-8119-dcf61b9c203a.png)

The first `ls` shows the content of the directory before running `PreffixSuffix`, and the second one shows the content after it. Do you have any idea of why this happenned?

**Comment by murraycu** [comment]
Maybe you would see something error messages if you started prefixsuffix from the command line.

**Comment by murraycu** [comment]
I think I found the problem. Could you please try with the latest code from git master?

**Comment by brunelli** [comment]
It's working as expected with the latest commit. Thank you!
